name: fluido
description: A simple and lightweight package to efficiently create reactive and responsive user interfaces in Flutter.
version: 0.1.1
homepage: https://github.com/bewond/fluido

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  #
  pedantic: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
